export const PORTFOLIO_DATA = {
  name: "Zulfikar Chamim",
  role: "Full-Stack & AI Engineer.",
  bio: "As a Full-Stack & AI Engineer, I thrive on connecting ideas with innovation, transforming complex concepts into robust, intelligent, and user-friendly solutions.",
  about: "I've been designing and developing websites for over 6 years. I love working at the intersection of technology and creativity, always striving to deliver exceptional user experiences.",
  email: "fikarchamiiiim@gmail.com",
  socials: {
    github: "https://github.com/fikarchamiiiim",
    linkedin: "https://linkedin.com/in/zulfikar-chamim",
  },
  skills: [
    "Python",
    "FastAPI",
    "Django",
    "React",
    "Next.js",
    "React Native",
    "Kotlin",
    "TensorFlow",
    "PyTorch",
    "Scikit-learn",
    "Keras",
    "Docker", 
    "Kubernetes", 
    "CI/CD", 
    "GCP", 
    "Google Gemini"
],
  projects: [
    {
      id: "1",
      title: "SentimentLens",
      description: "Real-time sentiment analysis platform for social media streams. Processes tweets and posts using fine-tuned BERT models, visualizing trends through an interactive Next.js dashboard deployed on GCP.",
      tags: ["Python", "PyTorch", "FastAPI", "Next.js", "GCP"],
      link: "#",
      image: "https://picsum.photos/seed/sentimentlens/800/600",
    },
    {
      id: "2",
      title: "GeminiDoc AI",
      description: "Intelligent document assistant powered by Google Gemini. Upload PDFs or docs and get context-aware Q&A, summaries, and knowledge extraction via a clean React interface backed by a FastAPI service.",
      tags: ["Google Gemini", "FastAPI", "React", "Docker"],
      link: "#",
      image: "https://picsum.photos/seed/geminidoc/800/600",
    },
    {
      id: "3",
      title: "TrackFit Mobile",
      description: "Cross-platform fitness tracker built with React Native and Kotlin modules for native sensor access. Features AI-powered workout recommendations using a Scikit-learn model served via Django REST API.",
      tags: ["React Native", "Kotlin", "Django", "Scikit-learn"],
      link: "#",
      image: "https://picsum.photos/seed/trackfit/800/600",
    },
    {
      id: "4",
      title: "MLFlow Orchestrator",
      description: "End-to-end ML pipeline orchestration system. Automates model training, evaluation, and deployment using containerized microservices with CI/CD pipelines and Kubernetes-based autoscaling on GCP.",
      tags: ["Python", "Docker", "Kubernetes", "CI/CD", "GCP"],
      link: "#",
      image: "https://picsum.photos/seed/mlflow/800/600",
    },
    {
      id: "5",
      title: "VisionShop",
      description: "E-commerce platform with AI visual search — snap a photo to find similar products. Built with a Next.js storefront, a Keras-based image embedding engine, and a FastAPI inference service.",
      tags: ["Next.js", "Keras", "FastAPI", "TensorFlow"],
      link: "#",
      image: "https://picsum.photos/seed/visionshop/800/600",
    },
    {
      id: "6",
      title: "DevPulse Analytics",
      description: "Developer productivity analytics dashboard that aggregates GitHub, Jira, and CI/CD metrics. React frontend with Django backend, containerized via Docker and deployed with automated GCP Cloud Run pipelines.",
      tags: ["React", "Django", "Docker", "CI/CD", "GCP"],
      link: "#",
      image: "https://picsum.photos/seed/devpulse/800/600",
    },
  ]
};
