export const PORTFOLIO_DATA = {
  name: "Zulfikar Chamim",
  role: "Full-Stack & AI Engineer.",
  bio: "As a Full-Stack & AI Engineer, I thrive on connecting ideas with innovation, transforming complex concepts into robust, intelligent, and user-friendly solutions.",
  about: "I've been designing and developing websites for over 6 years. I love working at the intersection of technology and creativity, always striving to deliver exceptional user experiences.",
  email: "fikarchamiiiim@gmail.com",
  socials: {
    github: "https://github.com/fikarchamiiiim",
    linkedin: "https://linkedin.com/in/zulfikar-chamim",
  },
  skills: [
    "Python",
    "FastAPI",
    "Django",
    "React",
    "Next.js",
    "React Native",
    "Kotlin",
    "TensorFlow",
    "PyTorch",
    "Scikit-learn",
    "Keras",
    "Docker", 
    "Kubernetes", 
    "CI/CD", 
    "GCP", 
    "Google Gemini"
],
  projects: [
    {
      id: "1",
      title: "Military Grade Bombing Scoring System",
      description: "An advanced hardware-integrated scoring platform for Indonesian Air Force (LITBANG AU). Developed a real-time GUI and REST API to process ballistic calculations and synchronize training data with a centralized web dashboard.",
      tags: ["Python", "PyQT", "REST API", "Hardware Integration", "Data Analytics"],
      link: "#",
      image: "https://picsum.photos/seed/military-grade-bombing-scoring-system/800/600",
    },
    {
      id: "2",
      title: "Smart City IoT: Singapore Street Lighting Dashboard",
      description: "An end-to-end monitoring solution for Singapore's urban infrastructure. Built a robust backend and interactive dashboard to visualize sensor data from street lights, providing real-time reporting and maintenance insights.",
      tags: ["Python", "FastAPI", "IoT", "Data Visualization", "Backend"],
      link: "#",
      image: "https://picsum.photos/seed/smart-city-iot/800/600",
    },
    {
      id: "3",
      title: "AI Visual Action Narrator (Video Captioning)",
      description: "An intelligent computer vision application that utilizes Deep Learning to analyze video streams and automatically generate descriptive text captions of human actions in real-time.",
      tags: ["Python", "AI", "Machine Learning", "Deep Learning", "Computer Vision"],
      link: "#",
      image: "https://picsum.photos/seed/ai-visual-action-narrator/800/600",
    },
    {
      id: "4",
      title: "Biometric Facial Symmetry Engine",
      description: "A high-precision biometric tool using Face Landmark models to detect and calculate facial patterns. Features a custom-built GUI for detailed symmetry analysis and pattern mapping.",
      tags: ["Python", "Computer Vision", "Face Landmark", "PySide/PyQT"],
      link: "#",
      image: "https://picsum.photos/seed/biometric-facial-symmetry-engine/800/600",
    },
    {
      id: "5",
      title: "Universal PTZ Camera Control Library",
      description: "Developed a custom Python module to unify hardware communication protocols for industrial PTZ cameras (OKAF & Hikvision), enabling seamless automation and control integration.",
      tags: ["Python", "Hardware Integration", "Library Development", "IoT"],
      link: "#",
      image: "https://picsum.photos/seed/universal-ptz-camera-control-library/800/600",
    },
    {
      id: "6",
      title: "Tacview Telemetry Data Exporter",
      description: "A specialized data processing utility designed to convert raw flight/simulation telemetry data into compatible formats for Tacview, facilitating advanced mission debriefing and analysis.",
      tags: ["Python", "Data Processing", "Telemetry", "File Conversion"],
      link: "#",
      image: "https://picsum.photos/seed/tacview-telemetry-data-exporter/800/600",
    }
  ]
};
